# Generated by Django 2.1.7 on 2019-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Klassika', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(default='Klassika', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Klassika', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
