# Generated by Django 2.1.7 on 2019-05-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190506_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='book_info',
        ),
        migrations.AddField(
            model_name='post',
            name='book_info',
            field=models.ManyToManyField(to='api.Book'),
        ),
    ]
