# Generated by Django 2.2.1 on 2019-05-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190511_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_by',
            new_name='created_by',
        ),
    ]
